[2025-05-19 00:02:47] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:02:47] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:02:52] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:02:52] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:02:57] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:02:57] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:02] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:02] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:07] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:07] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:12] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:12] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:17] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:17] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:22] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:22] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:27] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:27] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:32] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:32] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:37] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:37] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:42] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:42] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:47] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:47] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:52] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:52] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:03:57] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:03:57] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:02] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:02] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:07] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:07] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:12] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:12] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:17] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:17] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:22] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:22] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:27] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:27] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:32] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:32] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:37] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:37] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:42] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:42] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:47] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:47] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:52] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:52] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:04:57] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:04:57] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:02] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:03] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:08] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:08] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:13] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:13] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:18] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:18] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:23] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:23] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:28] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:28] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:33] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:33] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:38] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:38] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:43] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:43] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:48] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:48] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:53] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:53] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:05:58] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:05:58] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:03] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:03] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:08] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:08] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:13] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:13] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:18] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:18] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:23] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:23] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:28] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:28] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:33] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:33] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:38] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:38] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:43] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:43] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:48] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:48] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:53] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:53] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:06:58] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:06:58] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:07:03] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:07:03] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:07:08] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:07:08] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:07:13] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:07:13] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:07:18] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:07:18] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:07:23] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:07:23] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:07:28] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:07:28] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:07:56] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:07:56] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:01] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:02] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:07] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:07] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:12] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:12] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:17] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:17] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:22] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:22] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:27] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:27] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:32] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:32] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:37] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:37] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:42] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:42] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:47] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:47] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:52] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:52] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:08:57] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:08:57] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:02] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:02] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:07] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:07] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:12] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:12] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:17] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:17] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:22] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:22] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:27] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:27] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:32] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:32] тЪая╕П Bot exited with code 2; restarting in 5s
[2025-05-19 00:09:37] ЁЯЪА Starting bot
python3: can't open file '/workspace/0dte/scripts/main.py': [Errno 2] No such file or directory
[2025-05-19 00:09:37] тЪая╕П Bot exited with code 2; restarting in 5s
